
services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566" # LocalStack Gateway
      - "4571:4571" # External services (edge)
    environment:
      - SERVICES=s3,lambda,dynamodb
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock